spec:
  template:
    spec:
      containers:
        - volumeMounts:
            - name: config
              mountPath: /app/config
          env:
            - name: JAVA_OPTIONS
              value: "-Dswarm.project.stage=prod -Dswarm.project.stage.file=file:///app/config/project-stages.yml"
      volumes:
        - configMap:
            name: inventory
            items:
            - key: "project-stages.yml"
              path: "project-stages.yml"
          name: config

apiVersion: v1
kind: DeploymentConfig
metadata:
  name: inventory
  labels:
    app: coolstore
    application: coolstore
    component: inventory
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 3600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - inventory
        from:
          kind: ImageStreamTag
          namespace: coolstore
          name: 'inventory:latest'
  replicas: 1
  selector:
    component: inventory
    deploymentconfig: inventory
  template:
    metadata:
      labels:
        component: inventory
        deploymentconfig: inventory
    spec:
      volumes:
        - name: config
          configMap:
            name: inventory
            items:
              - key: project-stages.yml
                path: project-stages.yml
      containers:
        - name: inventory
          image: inventory
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: jolokia
              containerPort: 8787
              protocol: TCP
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: AB_JOLOKIA_OFF
              value: 'true'
            - name: JAVA_OPTIONS
              value: >-
                -Dswarm.project.stage=prod
                -Dswarm.project.stage.file=file:///app/config/project-stages.yml
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /app/config
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst