spec:
  template:
    spec:
      containers:
        - volumeMounts:
            - name: config
              mountPath: /app/config
          env:
            - name: JAVA_OPTIONS
              value: "-Dswarm.project.stage=prod -Dswarm.project.stage.file=file:///app/config/project-stages.yml"
      volumes:
        - configMap:
            name: inventory
            items:
            - key: "project-stages.yml"
              path: "project-stages.yml"
          name: config